name: Terraform GKE Cluster + Namespace

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy GKE and Namespace
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Write GCP credentials to file
        run: |
          echo "${GOOGLE_CREDENTIALS}" > gcp-sa-key.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="credentials_file=gcp-sa-key.json" -var="project_id=$PROJECT_ID"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="credentials_file=gcp-sa-key.json" -var="project_id=$PROJECT_ID"
